# Generated by Django 5.0.6 on 2024-06-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_cinema_cinema_id_alter_city_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_images/'),
        ),
    ]
