# Generated by Django 5.0.6 on 2024-06-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_movie_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/movie_images'),
        ),
    ]
